CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Blog remains on the content/zhparser PostgreSQL instance (currently PG16).
-- Classification identities are UUIDv7 generated by the Go adapter/seed and
-- are therefore required explicitly instead of depending on database-generated UUIDs.

CREATE TABLE posts (
    id             UUID PRIMARY KEY,
    author_id      TEXT NOT NULL,
    post_type      TEXT NOT NULL DEFAULT 'post',
    title          TEXT NOT NULL,
    slug           TEXT NOT NULL,
    content        TEXT NOT NULL DEFAULT '',
    excerpt        TEXT NOT NULL DEFAULT '',
    cover_asset_id TEXT NOT NULL DEFAULT '',
    cover_url      TEXT NOT NULL DEFAULT '',
    comment_status SMALLINT NOT NULL DEFAULT 1,
    status         TEXT NOT NULL DEFAULT 'draft',
    locale         TEXT NOT NULL DEFAULT 'zh-CN',
    published_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_posts_slug       ON posts (slug) WHERE deleted_at IS NULL;
CREATE INDEX        ix_posts_status_time ON posts (status, published_at DESC);
CREATE INDEX        ix_posts_author      ON posts (author_id);

CREATE TABLE post_stats (
    post_id       UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    view_count    BIGINT NOT NULL DEFAULT 0,
    like_count    BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    share_count   BIGINT NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE post_seo (
    post_id         UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
    meta_title      TEXT NOT NULL DEFAULT '',
    meta_desc       TEXT NOT NULL DEFAULT '',
    og_title        TEXT NOT NULL DEFAULT '',
    og_image        TEXT NOT NULL DEFAULT '',
    canonical_url   TEXT NOT NULL DEFAULT '',
    robots          TEXT NOT NULL DEFAULT '',
    structured_data JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE post_metas (
    id         UUID PRIMARY KEY,
    post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    meta_key   TEXT NOT NULL,
    meta_value TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX uq_post_metas_key ON post_metas (post_id, meta_key);

CREATE TABLE post_revisions (
    id         UUID PRIMARY KEY,
    post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    author_id  TEXT NOT NULL,
    title      TEXT NOT NULL,
    content    TEXT NOT NULL,
    rev_note   TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ix_post_revisions_post ON post_revisions (post_id, created_at DESC);

CREATE TABLE blog_classification_catalogs (
    id          UUID PRIMARY KEY,
    catalog_key TEXT NOT NULL UNIQUE CHECK (catalog_key = 'blog'),
    revision    BIGINT NOT NULL DEFAULT 1 CHECK (revision > 0),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE blog_categories (
    id                  UUID PRIMARY KEY,
    catalog_id          UUID NOT NULL REFERENCES blog_classification_catalogs(id),
    parent_id           UUID,
    current_name        TEXT NOT NULL,
    current_slug        TEXT NOT NULL,
    description         TEXT NOT NULL DEFAULT '',
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'inactive', 'replaced')),
    editorial_position  INT,
    first_activated_at  TIMESTAMPTZ,
    replacement_id      UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (catalog_id, id),
    UNIQUE (catalog_id, current_slug),
    FOREIGN KEY (catalog_id, parent_id) REFERENCES blog_categories(catalog_id, id),
    FOREIGN KEY (catalog_id, replacement_id) REFERENCES blog_categories(catalog_id, id),
    CHECK (parent_id IS NULL OR parent_id <> id),
    CHECK ((status = 'active' AND first_activated_at IS NOT NULL) OR status <> 'active'),
    CHECK ((status = 'replaced' AND replacement_id IS NOT NULL) OR (status <> 'replaced' AND replacement_id IS NULL))
);
CREATE INDEX blog_categories_parent_idx ON blog_categories (catalog_id, parent_id);
CREATE INDEX blog_categories_replacement_idx ON blog_categories (catalog_id, replacement_id) WHERE replacement_id IS NOT NULL;

CREATE TABLE blog_tags (
    id                  UUID PRIMARY KEY,
    catalog_id          UUID NOT NULL REFERENCES blog_classification_catalogs(id),
    current_name        TEXT NOT NULL,
    current_slug        TEXT NOT NULL,
    description         TEXT NOT NULL DEFAULT '',
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'inactive', 'replaced')),
    first_activated_at  TIMESTAMPTZ,
    replacement_id      UUID,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (catalog_id, id),
    UNIQUE (catalog_id, current_slug),
    FOREIGN KEY (catalog_id, replacement_id) REFERENCES blog_tags(catalog_id, id),
    CHECK ((status = 'active' AND first_activated_at IS NOT NULL) OR status <> 'active'),
    CHECK ((status = 'replaced' AND replacement_id IS NOT NULL) OR (status <> 'replaced' AND replacement_id IS NULL))
);
CREATE INDEX blog_tags_name_cursor_idx ON blog_tags (LOWER(current_name), id);
CREATE INDEX blog_tags_replacement_idx ON blog_tags (catalog_id, replacement_id) WHERE replacement_id IS NOT NULL;

CREATE TABLE blog_tag_lookup_entries (
    catalog_id    UUID NOT NULL REFERENCES blog_classification_catalogs(id),
    lookup_key    TEXT NOT NULL,
    target_tag_id UUID NOT NULL,
    kind          TEXT NOT NULL CHECK (kind IN ('canonical', 'alias')),
    display_value TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (catalog_id, lookup_key),
    FOREIGN KEY (catalog_id, target_tag_id) REFERENCES blog_tags(catalog_id, id)
);
CREATE INDEX blog_tag_lookup_target_idx ON blog_tag_lookup_entries (target_tag_id);

CREATE TABLE blog_classification_policy_profiles (
    catalog_id       UUID NOT NULL REFERENCES blog_classification_catalogs(id),
    policy_key       TEXT NOT NULL,
    schema_version   SMALLINT NOT NULL CHECK (schema_version = 1),
    policy_revision  BIGINT NOT NULL CHECK (policy_revision > 0),
    category_policy  JSONB NOT NULL,
    facet_policies   JSONB NOT NULL DEFAULT '[]',
    tag_policy       JSONB NOT NULL,
    discovery_policy JSONB NOT NULL,
    PRIMARY KEY (catalog_id, policy_key)
);

CREATE TABLE blog_post_category_assignments (
    post_id     UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES blog_categories(id),
    PRIMARY KEY (post_id, category_id)
);
CREATE INDEX blog_post_category_filter_idx ON blog_post_category_assignments (category_id, post_id);

CREATE TABLE blog_post_tag_assignments (
    post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id  UUID NOT NULL REFERENCES blog_tags(id),
    PRIMARY KEY (post_id, tag_id)
);
CREATE INDEX blog_post_tag_filter_idx ON blog_post_tag_assignments (tag_id, post_id);

CREATE TABLE post_likes (
    user_id    TEXT NOT NULL,
    post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post_bookmarks (
    user_id    TEXT NOT NULL,
    post_id    UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, post_id)
);
