name: yueli-blog-standalone

include:
  - path: deploy/includes/identity/compose.yaml
  - path:
      - deploy/includes/asset/compose.yaml
      - deploy/includes/asset/compose.managed-identity.yaml
  - path:
      - deploy/compose.blog.yaml
      - deploy/topologies/blog.standalone.yaml
