// Code generated by foundation httpcontract; DO NOT EDIT.

package blogerr

import (
	"sort"

	"github.com/yueli-official/foundation/go/problem"
)

const (
	CodeAbuseReplay                 = "blog.abuse_attempt_replayed"
	CodeAbuseUnavailable            = "blog.abuse_unavailable"
	CodeAssetTooLarge               = "blog.asset_too_large"
	CodeAuthorizationUnavailable    = "blog.authorization_unavailable"
	CodeChallengeRequired           = "blog.challenge_required"
	CodeCommentNotFound             = "blog.comment_not_found"
	CodeCommentRejected             = "blog.comment_rejected"
	CodeCommentsClosed              = "blog.comments_closed"
	CodeForbidden                   = "blog.forbidden"
	CodeInitialAdministratorClaimed = "blog.initial_administrator_already_claimed"
	CodeInvalidInput                = "blog.invalid_input"
	CodeInvalidState                = "blog.invalid_state"
	CodeNotFound                    = "blog.not_found"
	CodeRateLimited                 = "blog.rate_limited"
	CodeSlugTaken                   = "blog.slug_taken"
	CodeUpstreamFailed              = "blog.upstream_failed"
)

var descriptors = map[string]problem.Descriptor{
	CodeAbuseReplay:                 descriptor(CodeAbuseReplay, 409),
	CodeAbuseUnavailable:            descriptor(CodeAbuseUnavailable, 503),
	CodeAssetTooLarge:               descriptor(CodeAssetTooLarge, 413),
	CodeAuthorizationUnavailable:    descriptor(CodeAuthorizationUnavailable, 503),
	CodeChallengeRequired:           descriptor(CodeChallengeRequired, 403),
	CodeCommentNotFound:             descriptor(CodeCommentNotFound, 404),
	CodeCommentRejected:             descriptor(CodeCommentRejected, 422),
	CodeCommentsClosed:              descriptor(CodeCommentsClosed, 409),
	CodeForbidden:                   descriptor(CodeForbidden, 403),
	CodeInitialAdministratorClaimed: descriptor(CodeInitialAdministratorClaimed, 409),
	CodeInvalidInput:                descriptor(CodeInvalidInput, 400),
	CodeInvalidState:                descriptor(CodeInvalidState, 400),
	CodeNotFound:                    descriptor(CodeNotFound, 404),
	CodeRateLimited:                 descriptor(CodeRateLimited, 429),
	CodeSlugTaken:                   descriptor(CodeSlugTaken, 409),
	CodeUpstreamFailed:              descriptor(CodeUpstreamFailed, 502),
}

func descriptor(code string, status int) problem.Descriptor {
	return problem.MustDescriptor(problem.MustKind(code, status), "https://errors.yueli.dev/problems/"+code)
}

func DescriptorForCode(code string) (problem.Descriptor, bool) {
	value, ok := descriptors[code]
	return value, ok
}

type CatalogEntry struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

func Catalog() []CatalogEntry {
	result := make([]CatalogEntry, 0, len(descriptors))
	for code, value := range descriptors {
		result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })
	return result
}
